apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-19T12:27:53Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-node
  name: hello-node
  namespace: default
  resourceVersion: "8334"
  selfLink: /api/v1/namespaces/default/services/hello-node
  uid: bb9e3500-f817-499c-aa65-bc401dcfd6df
spec:
  clusterIP: 10.12.13.22
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30271
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.203.61.208
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-08-19T12:27:05Z"
  generation: 1
  labels:
    app: hello-node
  name: hello-node
  namespace: default
  resourceVersion: "8031"
  selfLink: /apis/apps/v1/namespaces/default/deployments/hello-node
  uid: 1c2c7970-b3b4-409a-82fe-7c19f47460a1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-node
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        imagePullPolicy: IfNotPresent
        name: echoserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-19T12:27:14Z"
    lastUpdateTime: "2020-08-19T12:27:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-08-19T12:27:05Z"
    lastUpdateTime: "2020-08-19T12:27:14Z"
    message: ReplicaSet "hello-node-bcbcd7f76" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
